### ISSUE TITLE
How to Copy all child nodes? 

### ISSUE THREAD

**Issue by azhar-sde** [tataelm/XmlNodeCloner#1]
This is great Tataelm, Please help me copy all child nodes with data? I've 100's of child and sub-child nodes in it. 

Please help me to copy them. Thanks I realy appreciate.

**Comment by tataelm** [comment]
Hi. Can you please post a portion of your xml text here?

**Comment by AzharSy3d** [comment]
<Group>
	<GroupData>
		<GroupId></GroupId>
		<FileId></FileId>
	</GroupData>
	<Persons>
		<Person>
			<PersonInfo>
				<transactionId>1234</transactionId>
				<sin>531347975</sin>
				<firstName>Rachel</firstName>
				<middleName>Test</middleName>
				<lastName>Lee</lastName>
				<maidenName>Park</maidenName>
				<dob>2000-01-01T05:00:00.0000000+00:00</dob>
				<suffix>JR</suffix>
				<dod></dod>
				<gender>F</gender>
				<maritalStatus>M</maritalStatus>
				<status>A</status>
				<indigenousStatus>No</indigenousStatus>
				<tobaccoStatus>N</tobaccoStatus>
				<por>NF</por>
				<depositBankInfo>Yes</depositBankInfo>
				<withdrawBankInfo>Yes</withdrawBankInfo>
				<paperlessDelivery>PS</paperlessDelivery>
				<languagePref>EN</languagePref>
				<Addresses>
				 <MemberAddress>
							 <addressType>P</addressType>
							 <addressEffDate>2022-03-01T05:00:00.0000000+00:00</addressEffDate>
							 <addressLine1>10 Red Road</addressLine1>
							 <addressLine2></addressLine2>
							 <addressLine3></addressLine3>
							 <city>Corner Brook</city>
							 <province>NF</province>
							 <country>CA</country>
							 <postalCode>V3F3A1</postalCode>
				 </MemberAddress>
				 <MemberAddress>
							 <addressType>C</addressType>
							 <addressEffDate>2022-03-01T05:00:00.0000000+00:00</addressEffDate>
							 <addressLine1>24 Blue Road</addressLine1>
							 <addressLine2></addressLine2>
							 <addressLine3></addressLine3>
							 <city>Quebec City</city>
							 <province>PQ</province>
							 <country>CA</country>
							 <postalCode>D3A1G4</postalCode>
				</MemberAddress>
				</Addresses>
			</PersonInfo>
		</Person>
	</Persons>
</Group>


I want to duplicate <person> inside <persons> I tried updating the code, It doesn't copy the nested nodes in the code. 
Lets have screen share if convinient. Thanks

**Comment by azhar-sde** [comment]
I want to duplicate PERSON tag inside PERSONS tags.  I tried updating the code, It doesn't copy the nested nodes in the code.
Let's have screen share if convenient. Thanks

Pleaes find  attached file.

[ModifiedXMLFormat.txt](https://github.com/tataelm/XmlNodeCloner/files/8661704/ModifiedXMLFormat.txt)

**Comment by tataelm** [comment]
I understand the problem. This solution doesn't cover child node iteration indeed. 

I could do a patch to it but as I am working full time on 2 different projects, it may take a while. It has been almost 2 years since I've shared this here. How urgent do you need it?

If you have already worked on the code, please try to iterate fillHashMapChildNodes function in itself, until you don't get any more child nodes.

**Comment by azhar-sde** [comment]
its pretty urjent for me, I've spent two days on this but couldn't found a proper solution.

I tried looping, but I was looking in getChildNodes().    I am working on a project, there I need to clone the Person and parse the file. HOpe you get time and we can get this resolved. 

I can share my screen whenever you are availaible.

**Comment by tataelm** [comment]
I see. There is a better way to do it. Why do you have to work with xml file in this case? You don't use attributes, only elements. And you are working with large files. 

1. https://freecodegenerators.com/code-converters/xml-to-java
Go this this site paste your xml and get a java class equivalent. Paste the necessary classes in your project.

2. https://stackoverflow.com/questions/16364547/how-to-parse-xml-to-java-object
Parse your object to java class. You will see every element as class fields and/or list of objects.

3. Do whatever you want to do with it. Modify it, copy it etc.. 

4. https://stackoverflow.com/questions/26959343/convert-java-object-to-xml-string
Convert your java object back to xml and overwrite your original file. 

I am already inbetween meetings. Only free day I have this week is thursday. But your issue shouldn't be covered by this XmlNodeCloner project.  What I've described above is the way to go. 

XML and JSON files shouldn't tampered with this dense. They are only there to pass the information.

**Comment by azhar-sde** [comment]
Thanks for quick response Tataem, Actually I am working on an import which requires giant xml input and parse it to java, process it and then store into the database. 

I'll definetly try above and see it serves my goal. 

You : 
XML and JSON files shouldn't tampered with this dense. They are only there to pass the information.

What are the best practices to deal with such huge imports? Reply whenever you get time :) nothing urject. 

I appreciate your help, Thanks Tataem.

**Comment by tataelm** [comment]
Please let me know if that serves your goal. 


**What are the best practices to deal with such huge imports?**
This is a subjective topic. How huge is the data? How many megabytes? Is the process on a server or on clients machine?

You need to consider it this way: XML file -> Memory -> Database. 
If you first read the data and then write it, right in between the both processes, you will have every single data on your memory. Most of the time memory can handle really huge data.

But let's say this process is on client's machine and your memory goes up to 100 mb from 10 mb. (You write 90 mb of files to memory before writing it to database.) and you want to avoid it. 

There could be many solutions to this but I will write the first thing that comes to my mind. 

1. You could try "database write while xml read". But since you can only read XML file once and parse it once, it seems you can't avoid writing it to the memory. Splitting an Xml file is a really risky way. You may not know the relations between nodes. (Note that I am not familiar with JAXB library that much. Maybe you can parse sequentially.)

2. Let's say you have a collection of objects, length of 100'000, which you've parsed from XML. As soon as you write an object to database, you can set it to null in the collection and run the garbage collector right afterwards. This way, that memory peak will last only milliseconds. 

3. If you really want to avoid that memory peak, you must get a splitted xml file to begin with. The code that exports it, could have max. limits. i.e. for every 1000 records, there can be a single xml file. 

I hope this helps you.

**Comment by azhar-sde** [comment]
The process will be on server, and hell yes we will be using that 'JAXB' to serve our purposes. The concern is when data is huge, we could multithread it. 

we are still not in final design phase, we've been working on tradeoff using XML or JSON. and people around says XML is faster and better. lets see where we get. 

"The reason I want XmlNodeCloner is to generate a huge XML data file in order to test our work for XML import. I'll try to find a work around, will refer the links you've provided. 

I really appreciate you taking time to reply in your busy schedule. Thanks man. Have a good day. 

Lets connect on LinkedIn https://www.linkedin.com/in/azhar-sde/.

**Comment by tataelm** [comment]
You are very welcome mate. 

If you are going to multithread on the same collection, please read about "volatile" keyword. This is always a problem, if different threads reach out to the same variable. When you make it volatile, it will stay threadsafe. 
https://www.baeldung.com/java-volatile

I am not on any social media but in a year or so I might have to join to linkedin, due to business related reasons. I will gladly add you there once im in.
